import mongoose, { Document, Schema } from 'mongoose';

export interface IOrder extends Document {
  userId: string; // username ของ user (เช่น demo_user)
  userDisplayName: string; // ชื่อที่แสดงของ user (เช่น Bakugoa ku)
  userAddress: string; // ที่อยู่ของ user
  shopId: string; // _id ของร้าน
  shopName: string; // ชื่อร้าน
  items: {
    name: string;
    details: string;
    price: number;
  }[];
  serviceTotal: number; // ราคาบริการรวม
  deliveryFee: number; // ค่าส่ง
  total: number; // ราคารวมทั้งหมด
  paymentMethod: 'wallet' | 'cash';
  status:
    | 'decision'
    | 'accepted'
    | 'waiting_rider'
    | 'rider_coming'
    | 'at_shop'
    | 'out_for_delivery'
    | 'in_progress'
    | 'deliverying'
    | 'completed'
    | 'cancelled';
  riderId?: string; // _id ของ rider ที่รับงาน ( set ตอน rider_coming )
  note?: string; // หมายเหตุจาก user
  merchantOrderId?: string; // _id จาก ordersformerchant เมื่อ copy มา
  ordersId?: string; // _id ใน orders collection เมื่อ accept แล้ว (ใช้กับ ordersformerchant)
  // Coin shop: เวลาเครื่องซัก/อบจะเสร็จ (ใช้ cron อัปเดต order status)
  coinWashFinishTime?: Date;
  coinDryFinishTime?: Date;
  coinWashDone?: boolean;
  coinDryDone?: boolean;
  // Coin shop: index ของเครื่องที่ใช้ (สำหรับเปลี่ยน ready → available เมื่อไรเดอร์มารับ)
  washMachineIndex?: number;
  dryMachineIndex?: number;
  createdAt?: Date; // Auto-generated by timestamps
  updatedAt?: Date; // Auto-generated by timestamps
}

/** Status ที่ใช้ใน OrderForMerchant (ตรงกับ label ที่แสดงใน merchant app) */
export type OrderForMerchantStatus =
  | 'decision'
  | 'Looking for rider'
  | 'Waiting for rider'
  | 'In progress'
  | 'Ready for pickup'
  | 'Delivering'
  | 'Completed'
  | 'cancelled';

/** แปลง Order status เป็น OrderForMerchant status */
export function orderStatusToMerchantStatus(status: string): OrderForMerchantStatus {
  const map: Record<string, OrderForMerchantStatus> = {
    waiting_rider: 'Waiting for rider',
    rider_coming: 'Waiting for rider',
    at_shop: 'In progress',
    in_progress: 'Ready for pickup',
    out_for_delivery: 'Ready for pickup',
    deliverying: 'Delivering',
    delivering: 'Delivering',
    completed: 'Completed',
  };
  return map[status] || (status as OrderForMerchantStatus);
}

/** แปลง merchant status (at_shop, in_progress, ...) เป็น OrderForMerchant status */
export function merchantInputToMerchantStatus(status: string): OrderForMerchantStatus {
  const map: Record<string, OrderForMerchantStatus> = {
    at_shop: 'In progress',
    waiting_rider: 'Waiting for rider',
    rider_coming: 'Waiting for rider',
    in_progress: 'Ready for pickup',
    out_for_delivery: 'Ready for pickup',
    deliverying: 'Delivering',
    delivering: 'Delivering',
    completed: 'Completed',
  };
  return map[status] || (status as OrderForMerchantStatus);
}

const OrderSchema: Schema = new Schema(
  {
    userId: { type: String, required: true, default: 'demo_user' },
    userDisplayName: { type: String, default: '' },
    userAddress: { type: String, default: '' },
    shopId: { type: String, required: true },
    shopName: { type: String, required: true },
    items: [
      {
        name: { type: String, required: true },
        details: { type: String },
        price: { type: Number, required: true },
      },
    ],
    serviceTotal: { type: Number, required: true },
    deliveryFee: { type: Number, required: true },
    total: { type: Number, required: true },
    paymentMethod: { type: String, enum: ['wallet', 'cash'], default: 'cash' },
    status: {
      type: String,
      enum: [
        'decision',
        'accepted',
        'waiting_rider',
        'rider_coming',
        'at_shop',
        'out_for_delivery',
        'in_progress',
        'deliverying',
        'completed',
        'cancelled',
      ],
      default: 'decision',
    },
    riderId: { type: String, required: false },
    note: { type: String, required: false },
    merchantOrderId: { type: Schema.Types.ObjectId, ref: 'OrderForMerchant', required: false },
    ordersId: { type: Schema.Types.ObjectId, ref: 'Order', required: false },
    coinWashFinishTime: { type: Date, required: false },
    coinDryFinishTime: { type: Date, required: false },
    coinWashDone: { type: Boolean, required: false },
    coinDryDone: { type: Boolean, required: false },
    washMachineIndex: { type: Number, required: false },
    dryMachineIndex: { type: Number, required: false },
  },
  { timestamps: true }
);

export const Order = mongoose.model<IOrder>('Order', OrderSchema);

// รองรับทั้งค่าเก่า (rider_coming, at_shop, ...) และค่าใหม่ (Waiting for rider, ...) สำหรับ migration
const OrderForMerchantStatusEnum = [
  'decision',
  'Looking for rider',
  'Waiting for rider',
  'In progress',
  'Ready for pickup',
  'Delivering',
  'Completed',
  'cancelled',
  'rider_coming',
  'at_shop',
  'out_for_delivery',
  'in_progress',
  'deliverying',
  'completed',
] as const;
const OrderForMerchantSchema = new Schema(
  {
    ...OrderSchema.obj,
    status: {
      type: String,
      enum: OrderForMerchantStatusEnum,
      default: 'decision',
    },
  },
  { timestamps: true }
);

export const OrderForMerchant = mongoose.model<IOrder>(
  'OrderForMerchant',
  OrderForMerchantSchema,
  'ordersformerchant'
);
