import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#FFFFFF' },
    header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 10 },
    locationTitle: { fontSize: 12, color: '#999' },
    locationName: { fontSize: 16, fontWeight: 'bold', color: '#333' },
    searchSection: { paddingHorizontal: 16, paddingVertical: 10 },
    searchBar: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FAF5FF', borderRadius: 15, paddingHorizontal: 15, height: 50, borderWidth: 1, borderColor: '#F0E6FF' },
    searchInput: { flex: 1, marginHorizontal: 10, fontSize: 16 },
    filterContainer: { marginVertical: 10 },
    filterScroll: { paddingHorizontal: 16, gap: 8 },
    filterIconButton: { borderWidth: 1, borderColor: '#1d4685', borderRadius: 10, width: 40, height: 32, justifyContent: 'center', alignItems: 'center' },
    chip: { borderWidth: 1, borderColor: '#ddd', borderRadius: 20, paddingHorizontal: 15, height: 32, justifyContent: 'center', backgroundColor: '#fff' },
    chipText: { fontSize: 13, color: '#666' },
    activeChip: { backgroundColor: '#A0C4FF', borderColor: '#1d4685' },
    activeChipText: { color: '#1d4685', fontWeight: 'bold' },
    emptyContent: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    emptyText: { color: '#CCC', fontSize: 16, marginTop: 10 },
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)' },
    bottomSheetContainer: { position: 'absolute', bottom: 0, width: '100%', backgroundColor: 'white', borderTopLeftRadius: 25, borderTopRightRadius: 25, padding: 24 },
    modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
    bottomSheetTitle: { fontSize: 20, fontWeight: 'bold' },
    sectionTitle: { fontSize: 16, fontWeight: 'bold', marginVertical: 15 },
    row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
    rowLeft: { flexDirection: 'row', alignItems: 'center' },
    iconBox: { width: 30, marginRight: 15 },
    rowLabel: { fontSize: 16 },
    radioOuter: { width: 22, height: 22, borderRadius: 11, borderWidth: 2, borderColor: '#ccc', justifyContent: 'center', alignItems: 'center' },
    radioActive: { borderColor: '#1d4685' },
    radioInner: { width: 12, height: 12, borderRadius: 6, backgroundColor: '#1d4685' },
    checkbox: { width: 22, height: 22, borderRadius: 5, borderWidth: 2, borderColor: '#ccc', justifyContent: 'center', alignItems: 'center' },
    checkboxActive: { backgroundColor: '#1d4685', borderColor: '#1d4685' },
    priceContainer: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20 },
    priceBtnItem: { flex: 1, height: 40, borderWidth: 1, borderColor: '#1d4685', borderRadius: 20, justifyContent: 'center', alignItems: 'center', marginHorizontal: 4 },
    priceBtnActive: { backgroundColor: '#1d4685' },
    priceBtnText: { color: '#23a517ff', fontWeight: 'bold' },
    priceBtnTextActive: { color: '#fff' },
    bottomSheetFooter: { flexDirection: 'row', gap: 15, marginTop: 10 },
    resetBtn: { flex: 1, paddingVertical: 14, backgroundColor: '#a3b7d2', borderRadius: 25, alignItems: 'center' },
    applyBtn: { flex: 1, paddingVertical: 14, backgroundColor: '#a3b7d2', borderRadius: 25, alignItems: 'center' },
    resetBtnText: { fontWeight: 'bold' },
    applyBtnText: { fontWeight: 'bold' },
    shopListContainer: { flex: 1, paddingHorizontal: 16, paddingTop: 10 },
    shopCard: { flexDirection: 'row', marginBottom: 16, backgroundColor: '#fff', borderRadius: 12, overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 3 },
    shopImage: { width: 120, height: 120, backgroundColor: '#F0F0F0', justifyContent: 'center', alignItems: 'center' },
    shopInfo: { flex: 1, padding: 12, justifyContent: 'space-between' },
    shopName: { fontSize: 16, fontWeight: 'bold', color: '#333', marginBottom: 4 },
    shopRating: { flexDirection: 'row', alignItems: 'center', marginBottom: 4 },
    ratingText: { fontSize: 14, fontWeight: '600', color: '#333', marginLeft: 4 },
    ratingCount: { fontSize: 12, color: '#666', marginLeft: 4 },
    shopDetails: { flexDirection: 'row', alignItems: 'center', marginBottom: 4, flexWrap: 'wrap' },
    priceLevel: { fontSize: 14, fontWeight: 'bold', color: '#23a517ff', marginRight: 8 },
    shopType: { fontSize: 12, color: '#666', marginRight: 8 },
    deliveryInfo: { fontSize: 12, color: '#666' },
});